
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 07 17:51:23 CST 2014
//----------------------------------------------------

package AnalizadorInteligencia;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int menosy = 6;
  public static final int menosx = 4;
  public static final int verificar = 8;
  public static final int parentesisAbre = 17;
  public static final int decimal = 15;
  public static final int tokenelse = 12;
  public static final int tokenwhile = 13;
  public static final int parentesisCierre = 18;
  public static final int masy = 7;
  public static final int masx = 5;
  public static final int def = 14;
  public static final int elseif = 11;
  public static final int EOF = 0;
  public static final int bomba = 2;
  public static final int espera = 9;
  public static final int tokenif = 10;
  public static final int move = 3;
  public static final int error = 1;
  public static final int errorLexico = 22;
  public static final int llavesAbre = 19;
  public static final int llavesCierre = 20;
  public static final int puntoComa = 21;
  public static final int identificador = 16;
}

