
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Dec 28 17:28:10 CST 2013
//----------------------------------------------------

package AnalizadorRecursos;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int corazones = 6;
  public static final int ruta = 17;
  public static final int escenario = 2;
  public static final int enemigo = 4;
  public static final int obstaculo = 8;
  public static final int algoritmo = 7;
  public static final int dest = 9;
  public static final int corazon = 15;
  public static final int llaveAbre = 19;
  public static final int v = 10;
  public static final int bombar = 12;
  public static final int llaveCierre = 20;
  public static final int EOF = 0;
  public static final int bomba = 14;
  public static final int error = 1;
  public static final int errorLexico = 21;
  public static final int entero = 16;
  public static final int f = 11;
  public static final int dosPuntos = 18;
  public static final int heroe = 3;
  public static final int fuego = 13;
  public static final int identificador = 22;
  public static final int img = 5;
}

