
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 07 12:23:42 CST 2014
//----------------------------------------------------

package AnalizadorEscenario;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int rango = 5;
  public static final int coma = 6;
  public static final int parentesisAbre = 7;
  public static final int errorLexico = 9;
  public static final int EOF = 0;
  public static final int asignacion = 3;
  public static final int puntoComa = 4;
  public static final int entero = 2;
  public static final int error = 1;
  public static final int parentesisCierre = 8;
  public static final int identificador = 10;
}

